#!/bin/bash

if [[ $1 = "-help" ]] || [[ $1 = "-?" ]] || [[ $1 = "-h" ]]; then
    printf "usage: install <context>\r\n"
    printf "\r\n"
    printf "Call install for the specified context; the default is 'tools'.  May not be valid for all contexts.\r\n"
    printf "\r\n"
    exit 0
fi

CONTEXT=$1

if [[ -z $1 ]]; then
    CONTEXT="tools"
fi

COMMAND="install"

cd ./common
./exec.sh ${CONTEXT} $COMMAND
cd ..
