#!/bin/bash

if [[ $_ != $0 ]]; then # && echo "Script is being sourced" || echo "Script is a subshell"
    pushd ./common
    source init.sh
    popd

    pushd ../../
    cp ./.bam/build/dotdotdotdot/build.bam ./build.bam
    cp ./.bam/build/symlink ./symlink
    popd

    pushd ./lib
    ../symlink common `pwd`/../common
    popd

    pushd ./tools
    ../symlink common `pwd`/../common
    popd

    pushd ./tests
    ../symlink common `pwd`/../common
    popd
else
    printf "please source this script: 'source $0'";
fi
