#!/bin/bash

if [[ $_ != $0 ]]; then # && echo "Script is being sourced" || echo "Script is a subshell"
    pushd ./common
    source init.sh
    popd

    pushd ../../
    cp ./.bam/build/dotdotdotdot/build.sh ./build.sh
    cp ./.bam/build/symlink ./symlink
    popd
else
    printf "please source this script: 'source $0'";
fi
