#!/bin/bash

function symlink(){
    LINK=$1
    DEST=$2
    echo ""${OSTYPE}": Creating link ${LINK} => ${DEST}"
    if [[ "${OSTYPE}" == "linux-gnu" || "${OSTYPE}" == "freebsd"* || "${OSTYPE}" == "darwin"* ]]; then
        echo "using ln"
        sudo ln -s ${DEST} ${LINK}
    fi
    if [[ "${OSTYPE}" == "cygwin" || "${OSTYPE}" == "msys" ]]; then
        MKLINKDEST="${2////\\}"
        if [[ $MKLINKDEST = \\c\\* ]]; then
            MKLINKDEST=`echo ${MKLINKDEST} | cut -c3-1024`
            MKLINKDEST="C:${MKLINKDEST}"
        fi
        echo "using mklink: Link=${LINK} DEST=${MKLINKDEST}"
        if [[ -d ${DEST} ]]; then
            cmd <<< "mklink /D ${LINK} ${MKLINKDEST}" 
        else
            cmd <<< "mklink ${LINK} ${MKLINKDEST}"
        fi
    fi
}

LINK=$1
DEST=$2

symlink ${LINK} ${DEST}